const NOTHING_CHANGE = 'NOTHING_CHANGE'
const CHANGE_STAGE = 'CHANGE_STAGE'
const TAKE_ELEMENT_FROM_STAGE = 'TAKE_ELEMENT_FROM_STAGE'
const PUT_ELEMENT_INTO_POCKET = 'PUT_ELEMENT_INTO_POCKET'
const TAKE_ELEMENT_FROM_POCKET = 'TAKE_ELEMENT_FROM_POCKET'
const PUT_ELEMENT_INTO_STAGE = 'TAKE_ELEMENT_INTO_STAGE'
const ADD_MESSAGE = 'ADD_MESSAGE'
const CHANGE_ACTOR_STAGE = 'CHANGE_ACTOR_STAGE'
const ADD_COMMAND = 'ADD_COMMAND'
const SET_PREVIOUS_COMMAND_HISTORY_POSITION =
  'SET_PREVIOUS_COMMAND_HISTORY_POSITION '
const SET_NEXT_COMMAND_HISTORY_POSITION =
  'SET_NEXT_COMMAND_HISTORY_POSITION '

export {
  NOTHING_CHANGE,
  CHANGE_STAGE,
  TAKE_ELEMENT_FROM_STAGE,
  PUT_ELEMENT_INTO_POCKET,
  TAKE_ELEMENT_FROM_POCKET,
  PUT_ELEMENT_INTO_STAGE,
  ADD_MESSAGE,
  CHANGE_ACTOR_STAGE,
  ADD_COMMAND,
  SET_PREVIOUS_COMMAND_HISTORY_POSITION,
  SET_NEXT_COMMAND_HISTORY_POSITION
}
