const NOTHING_CHANGE = 'NOTHING_CHANGE'
const CHANGE_STAGE = 'CHANGE_STAGE'
const TAKE_ELEM_FROM_STAGE = 'TAKE_ELEM_FROM_STAGE'
const PUT_ELEM_INTO_POCKET = 'PUT_ELEM_INTO_POCKET'
const TAKE_ELEM_FROM_POCKET = 'TAKE_ELEM_FROM_POCKET'
const PUT_ELEM_INTO_STAGE = 'TAKE_ELEM_INTO_STAGE'

export {
  NOTHING_CHANGE,
  CHANGE_STAGE,
  TAKE_ELEM_FROM_STAGE,
  PUT_ELEM_INTO_POCKET,
  TAKE_ELEM_FROM_POCKET,
  PUT_ELEM_INTO_STAGE
}
